Run by cron
pyronear/pyro-engine pull request #69
Opened 2022-02-13 17:45 UTC by MateoLostanlen

This script allows to capture an image every 30s on the pi zero and send it to the central pi

For the moment it is launched in background using `python3 /home/pi/pi_zeros/runner.py &` but it is not very stable

I suggest to use a crontab instead which will launch a loop of two captures every minute:

`*/1 * * * * python3 /home/pi/pi_zeros/runner.py`

2022-02-14 08:59 UTC, fe51 requested changes
Hi, thanks for the PR !
 
How did you spot the instability of the current process? In any case, the proposed approach via a crontab sounds good to me !

I have juste made some naming suggestion. If for variable naming suggestion, it is open to discussion (name might be too long now haha,  or a comment to make it clear it is about seconds ?), I think it's good to specify the time unit in the parser desc.

2022-02-14 08:59 UTC, fe51 commented on pyroengine/pi_utils/pi_zeros/runner.py
> +    parser.add_argument('--loop_interval', default=30, action='store_true', help='Time between two photos')
```suggestion
    parser.add_argument('--loop_interval', default=30, action='store_true', help='Time in seconds between two photos')
```

2022-02-14 08:59 UTC, fe51 commented on pyroengine/pi_utils/pi_zeros/runner.py
> +    def __init__(self, webserver_url, loop_interval=30, max_iteration=None):
```suggestion
    def __init__(self, webserver_url, loop_interval_s=30, max_iteration=None):
```

2022-02-14 08:59 UTC, fe51 commented on pyroengine/pi_utils/pi_zeros/runner.py
>      CAPTURE_DELAY = 3
```suggestion
    CAPTURE_DELAY_S = 3
```

2022-02-14 08:59 UTC, fe51 commented on pyroengine/pi_utils/pi_zeros/runner.py
> -    LOOP_INTERVAL = 3
LOOP_INTERVAL_S = 3

2022-02-14 10:39 UTC, MateoLostanlen commented
Hi @fe51, thanks for your comments. Yes you are right it's better to specify time unit. I've made the change

I don't really know why the background task it's unstable but I notice that after a while the process stop :/

2022-02-14 10:46 UTC, fe51 approved these changes
Cool, thanks fo the quick updates !

In fact, it occured  to me that I had also seen on forums that it was perhaps not stable..
 who knows why !
 I do not know why, but as long as you've experienced that it's not stable, and regular short job cron runs seem to be more robust, let’s go for it !

2022-03-15 22:01 UTC, closed without merging

2022-03-15 22:02 UTC, MateoLostanlen commented
I'm closing this PR, let's use #74 instead