Update licence
pyronear/pyro-engine pull request #70
Opened 2022-02-14 12:16 UTC by fe51

Hi there, a PR to update the licence to apache 2.0, inspired by https://github.com/pyronear/pyro-vision/pull/132

It introduces the following changes : 
- updates licence to Apache 2.0
- updates headers
- adds script to check headers (copied from pyro-vision authored by frgfm)
- add ci job to check headers (copied from pyro-vision)

Happy to discuss it : especially, I am not knowledgeable in CI jobs so I do not know if its works.

2022-02-14 14:28 UTC, MateoLostanlen approved these changes
Thanks to bring it here too :)

2022-02-14 14:53 UTC, frgfm requested changes
Thanks a lot! There is only a small mistake on the copyright year :)

2022-02-14 14:53 UTC, frgfm commented on docs/source/conf.py
> +# Copyright (C) 2019-2022, Pyronear.
2020-2022 ;)

2022-02-14 17:16 UTC, fe51 commented on .github/validate_headers.py
> +starting_year = 2019
haha oops ! let's go for for commit on 30+ files :D

2022-02-14 17:28 UTC, fe51 commented
copyright year corrected :)

2022-02-14 17:29 UTC, MateoLostanlen approved these changes
thanks for the fix !

2022-02-16 07:42 UTC, fe51 commented
@frgfm I think we are good now !

2022-02-18 08:30 UTC, frgfm approved these changes
Cheers!

2022-02-18 10:04 UTC, merged